// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-cafe-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_cafe_info_default = defineTool({
  name: "get_cafe_info",
  title: "Get cafe info",
  description: "Basic info about the SO-HO! cafe/coworking: address, hours, contacts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          name: "SO-HO!",
          tagline: "Coffee \xB7 Work \xB7 Meet",
          address: "\u0414\u0430\u0447\u043D\u043E\u0435 \u0448\u043E\u0441\u0441\u0435, \u0434.22/3, \u041D\u043E\u0432\u043E\u0441\u0438\u0431\u0438\u0440\u0441\u043A",
          hours: "08:00\u201320:00",
          email: "hello@so-ho.ru",
          website: "https://so-ho.ru"
        })
      }
    ]
  })
});

// src/lib/mcp/tools/list-menu.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var MENU = [
  { id: "espresso", name: "\u042D\u0441\u043F\u0440\u0435\u0441\u0441\u043E", category: "coffee", group: "\u0447\u0435\u0440\u043D\u044B\u0439 \u043A\u043E\u0444\u0435", price: 180 },
  { id: "americano", name: "\u0410\u043C\u0435\u0440\u0438\u043A\u0430\u043D\u043E", category: "coffee", group: "\u0447\u0435\u0440\u043D\u044B\u0439 \u043A\u043E\u0444\u0435", price: 200 },
  { id: "cappuccino", name: "\u041A\u0430\u043F\u0443\u0447\u0438\u043D\u043E", category: "coffee", group: "\u043A\u043E\u0444\u0435 \u0441 \u043C\u043E\u043B\u043E\u043A\u043E\u043C", price: 280 },
  { id: "latte", name: "\u041B\u0430\u0442\u0442\u0435", category: "coffee", group: "\u043A\u043E\u0444\u0435 \u0441 \u043C\u043E\u043B\u043E\u043A\u043E\u043C", price: 300 },
  { id: "flat-white", name: "\u0424\u043B\u044D\u0442 \u0443\u0430\u0439\u0442", category: "coffee", group: "\u043A\u043E\u0444\u0435 \u0441 \u043C\u043E\u043B\u043E\u043A\u043E\u043C", price: 310 },
  { id: "raf-classic", name: "\u0420\u0430\u0444 \u043A\u043B\u0430\u0441\u0441\u0438\u0447\u0435\u0441\u043A\u0438\u0439", category: "coffee", group: "\u043A\u043E\u0444\u0435 \u0441 \u043C\u043E\u043B\u043E\u043A\u043E\u043C", price: 320 },
  { id: "raf-salt-caramel", name: "\u0420\u0430\u0444 \u0441\u043E\u043B\u0451\u043D\u0430\u044F \u043A\u0430\u0440\u0430\u043C\u0435\u043B\u044C", category: "coffee", group: "\u043A\u043E\u0444\u0435 \u0441 \u043C\u043E\u043B\u043E\u043A\u043E\u043C", price: 315, soldOut: true },
  { id: "cortado", name: "\u041A\u043E\u0440\u0442\u0430\u0434\u043E", category: "coffee", group: "\u043A\u043E\u0444\u0435 \u0441 \u043C\u043E\u043B\u043E\u043A\u043E\u043C", price: 260 },
  { id: "matcha-latte", name: "\u041C\u0430\u0442\u0447\u0430 \u043B\u0430\u0442\u0442\u0435", category: "nocoffee", group: "\u043C\u0430\u0442\u0447\u0430", price: 340 },
  { id: "matcha-banana", name: "\u041C\u0430\u0442\u0447\u0430 \u0431\u0430\u043D\u0430\u043D", category: "nocoffee", group: "\u043C\u0430\u0442\u0447\u0430", price: 375, soldOut: true },
  { id: "cocoa", name: "\u041A\u0430\u043A\u0430\u043E", category: "nocoffee", group: "\u043A\u0430\u043A\u0430\u043E", price: 290 },
  { id: "tea-hot", name: "\u0427\u0430\u0439\u043D\u044B\u0439 \u043A\u043E\u043A\u0442\u0435\u0439\u043B\u044C \xB7 \u0433\u043E\u0440\u044F\u0447\u0438\u0439", category: "nocoffee", group: "\u0447\u0430\u0439\u043D\u044B\u0435 \u043A\u043E\u043A\u0442\u0435\u0439\u043B\u0438", price: 260 },
  { id: "tea-cold", name: "\u0427\u0430\u0439\u043D\u044B\u0439 \u043A\u043E\u043A\u0442\u0435\u0439\u043B\u044C \xB7 \u0445\u043E\u043B\u043E\u0434\u043D\u044B\u0439", category: "nocoffee", group: "\u0447\u0430\u0439\u043D\u044B\u0435 \u043A\u043E\u043A\u0442\u0435\u0439\u043B\u0438", price: 290 },
  { id: "pistachio-latte", name: "\u0424\u0438\u0441\u0442\u0430\u0448\u043A\u043E\u0432\u044B\u0439 \u043B\u0430\u0442\u0442\u0435", category: "spring", group: "\u0432\u0435\u0441\u043D\u0430", price: 360, soldOut: true }
];
var list_menu_default = defineTool2({
  name: "list_menu",
  title: "List cafe menu",
  description: "List drinks from the SO-HO! cafe menu. Optionally filter by category.",
  inputSchema: {
    category: z.enum(["coffee", "nocoffee", "spring", "combo"]).optional().describe("Optional category filter."),
    include_sold_out: z.boolean().optional().describe("Include items that are temporarily out of stock. Default: true.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, include_sold_out }) => {
    const includeSoldOut = include_sold_out ?? true;
    const items = MENU.filter(
      (m) => (!category || m.category === category) && (includeSoldOut || !m.soldOut)
    );
    return {
      content: [{ type: "text", text: JSON.stringify(items) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/list-plans.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var PLANS = [
  { code: "fast", name: "Fast", description: "\u0411\u044B\u0441\u0442\u0440\u044B\u0439 \u0432\u0438\u0437\u0438\u0442: \u043A\u043E\u0444\u0435 \u0438 \u043C\u0435\u0441\u0442\u043E \u043D\u0430 \u043F\u0430\u0440\u0443 \u0447\u0430\u0441\u043E\u0432", duration: "\u0434\u043E 3 \u0447\u0430\u0441\u043E\u0432" },
  { code: "day", name: "Day Pass", description: "\u041F\u043E\u043B\u043D\u044B\u0439 \u0434\u0435\u043D\u044C \u0432 \u043A\u043E\u0432\u043E\u0440\u043A\u0438\u043D\u0433\u0435", duration: "1 \u0434\u0435\u043D\u044C" },
  { code: "flex", name: "Flex", description: "10 \u0434\u043D\u0435\u0439 \u0432 \u043C\u0435\u0441\u044F\u0446, \u0433\u0438\u0431\u043A\u0438\u0439 \u0433\u0440\u0430\u0444\u0438\u043A", duration: "30 \u0434\u043D\u0435\u0439" },
  { code: "fix", name: "Fix", description: "\u0417\u0430\u043A\u0440\u0435\u043F\u043B\u0451\u043D\u043D\u043E\u0435 \u043C\u0435\u0441\u0442\u043E, \u0431\u0435\u0437\u043B\u0438\u043C\u0438\u0442", duration: "30 \u0434\u043D\u0435\u0439" }
];
var list_plans_default = defineTool3({
  name: "list_plans",
  title: "List membership plans",
  description: "List SO-HO! coworking membership plans (Fast, Day, Flex, Fix).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PLANS) }],
    structuredContent: { plans: PLANS }
  })
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool4({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user identity (id and email) from the OAuth token.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const identity = { user_id: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(identity) }],
      structuredContent: identity
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yrykqeidmynochmowcwd";
var mcp_default = defineMcp({
  name: "so-ho-mcp",
  title: "SO-HO!",
  version: "0.1.0",
  instructions: "\u0418\u043D\u0441\u0442\u0440\u0443\u043C\u0435\u043D\u0442\u044B SO-HO! \u2014 \u043A\u043E\u0444\u0435\u0439\u043D\u0438 \u0438 \u043A\u043E\u0432\u043E\u0440\u043A\u0438\u043D\u0433\u0430 \u0432 \u041D\u043E\u0432\u043E\u0441\u0438\u0431\u0438\u0440\u0441\u043A\u0435. \u0418\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u0439 list_menu \u0434\u043B\u044F \u043C\u0435\u043D\u044E \u043A\u043E\u0444\u0435\u0439\u043D\u0438, list_plans \u0434\u043B\u044F \u0442\u0430\u0440\u0438\u0444\u043E\u0432 \u043A\u043E\u0432\u043E\u0440\u043A\u0438\u043D\u0433\u0430, get_cafe_info \u0434\u043B\u044F \u0430\u0434\u0440\u0435\u0441\u0430 \u0438 \u0447\u0430\u0441\u043E\u0432 \u0440\u0430\u0431\u043E\u0442\u044B, whoami \u0434\u043B\u044F \u043F\u0440\u043E\u0444\u0438\u043B\u044F \u0432\u043E\u0448\u0435\u0434\u0448\u0435\u0433\u043E \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_cafe_info_default, list_menu_default, list_plans_default, whoami_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
